In [2]:
!pip install transformers

In [4]:
# from transformers import AutoTokenizer,AutoModelForCasualLM
from transformers import AutoTokenizer, AutoModelForCausalLM

In [6]:
tokenizer = AutoTokenizer.from_pretrained('gpt2')
model=AutoModelForCausalLM.from_pretrained('gpt2')

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [7]:
# gready search
input=tokenizer("we are learning",return_tensors='pt')
output=model.generate(**input)
tokenizer.decode(output[0])


Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1178: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


"we are learning about the history of the world and the history of the world's people. We are"

In [9]:
# beam search
input=tokenizer("we are learning",return_tensors='pt')
output=model.generate(**input,num_beams=5)
tokenizer.decode(output[0])


Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1178: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


'we are learning more and more about what it means to be human. We are learning more and more'

In [11]:
# no repeate n-grams
input=tokenizer("we are learning",return_tensors='pt')
output=model.generate(**input,num_beams=5,
                      no_repeat_ngram_size=2,
                      max_new_tokens=100)
tokenizer.decode(output[0])



Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'we are learning more and more about what it means to be a human being.\n\n"It\'s not just about being human. It\'s about living in a world where you can do whatever you want with your life. And that\'s what we\'re doing. We\'re trying to make it a better place for all of us."<|endoftext|>'

In [13]:
# random sampling
input=tokenizer("we are learning",return_tensors='pt')
output=model.generate(**input,num_beams=5,
                      no_repeat_ngram_size=2,
                      max_new_tokens=100,
                      do_sample=True)
tokenizer.decode(output[0])


Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'we are learning how to make a difference," he said.\n\n"It\'s not just about the money. It\'s about what you can do to change the world. We\'re trying to do that every day. That\'s what we\'re doing right now."<|endoftext|>'

In [14]:
# temperature
input=tokenizer('we are learning',return_tensors='pt')
output=model.generate(**input,
                      max_new_tokens=50,
                      do_sample=True,
                      temperature=0.1)
tokenizer.decode(output[0])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'we are learning that the U.S. government is using the Internet to spy on Americans.\n\nThe NSA is using the Internet to spy on Americans.\n\nThe NSA is using the Internet to spy on Americans.\n\nThe NSA is using the Internet'

In [17]:
#  temperature
input=tokenizer('we are learning',return_tensors='pt')
output=model.generate(**input,
                      max_new_tokens=50,
                      do_sample=True,
                      temperature=0.0001)
tokenizer.decode(output[0])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


"we are learning about the history of the world and the history of the world's people. We are learning about the history of the world and the history of the world's people. We are learning about the history of the world and the history of the world's people"

In [19]:
# top k sampling
input=tokenizer('we are learning',return_tensors='pt')
output=model.generate(**input,
                      max_new_tokens=50,
                      do_sample=True,
                      top_k=50)
tokenizer.decode(output[0])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'we are learning from this experience.\n\nWhen asked how likely it is to cause problems when you try and break them, Dr Mark said: "It is very unlikely and I\'d say very unlikely."<|endoftext|>'

In [20]:
# top p sampling
input=tokenizer("we are learning",return_tensors='pt')
output=model.generate(**input,
                      max_new_tokens=50,
                      do_sample=True,
                      top_p=0.9)
tokenizer.decode(output[0])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'we are learning that, while many things are coming to pass on my journey, it was probably the best day of my life. At that point, the news of that moment that would become my final post in this blog is coming from my heart.\n\nWith'

In [21]:
import numpy as np

In [22]:
def softmax(x):
    return(np.exp(x)/np.exp(x).sum())

In [23]:
logits = np.array([-0.9, 0.3, 0.9, 0.4, 0.09])

In [24]:
softmax(logits)

array([0.05977181, 0.19844939, 0.36159836, 0.21932049, 0.16085995])

In [25]:
#softmax with temperatue
def softmax(x):
    return(np.exp(x/t)/np.exp(x/t).sum())

In [26]:
t=0.3
softmax(logits)

array([0.00177829, 0.09709144, 0.71741407, 0.13550202, 0.04821418])

In [27]:
t=2
softmax(logits)

array([0.11315083, 0.20617426, 0.27830614, 0.21674504, 0.18562374])

In [30]:
t=0.01
softmax(logits)

array([6.71418429e-79, 8.75651076e-27, 1.00000000e+00, 1.92874985e-22,
       6.63967720e-36])