In [1]:
!pip install transformers

In [2]:
import torch
from transformers import AutoTokenizer,AutoModelForCausalLM


In [3]:

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
model_name="gpt2-large"
tokenizer=AutoTokenizer.from_pretrained(model_name)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [5]:
model=AutoModelForCausalLM.from_pretrained(model_name).to(device)



model.safetensors:   0%|          | 0.00/3.25G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [13]:
input_text="I'm feeling well"
max_length=16


In [7]:
input_ids=tokenizer(input_text,return_tensors='pt')


In [8]:

input_ids

{'input_ids': tensor([[  40, 1101, 4203,  880]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [9]:
input_ids=input_ids['input_ids'].to(device)

In [14]:
output=model.generate(input_ids,max_length=max_length,num_beams=5,do_sample=False)


The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [15]:
output

tensor([[  40, 1101, 4203,  880,  553,  339,  531,   13,  366,   40, 1101, 4203,
          922,  526,  198,  198]], device='cuda:0')

In [16]:
print(tokenizer.decode(output[0]))

I'm feeling well," he said. "I'm feeling good."




In [18]:

output = model.generate(input_ids, max_length=max_length, num_beams=5,
                        do_sample=False, no_repeat_ngram_size=2)
tokenizer.decode(output[0])


The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'I\'m feeling well," he said. "It\'s just a matter of getting'

In [ ]:
# Nucleus Search

In [20]:
input_text="""This is good resource for geneai,
and its really helpful"""



In [19]:
max_length=128

In [28]:
input_ids=tokenizer(input_text,return_tensors='pt')


In [29]:
input_ids

{'input_ids': tensor([[1212,  318,  922, 8271,  329, 9779, 1872,   11,  198,  392,  663, 1107,
         7613]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [24]:
# input_ids=input_ids['input_ids']
# input_ids

tensor([[1212,  318,  922, 8271,  329, 9779, 1872,   11,  198,  392,  663, 1107,
         7613]])

In [30]:
input_ids=input_ids['input_ids'].to(device)
input_ids

tensor([[1212,  318,  922, 8271,  329, 9779, 1872,   11,  198,  392,  663, 1107,
         7613]], device='cuda:0')

In [31]:
output=model.generate(input_ids,max_length=max_length,do_sample=True,top_p=1)
output

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[ 1212,   318,   922,  8271,   329,  9779,  1872,    11,   198,   392,
           663,  1107,  7613,    11,   611,   345,   466,   340, 14500,   475,
           351,   262,  6133,   286,  4899,   588,   308,  9945,   612,   389,
           257,  1256,   286,  4831,   284,  1011,   284,   787,  9779,  1872,
           257,  2829,  2891,   475,   262,  2891,  2346,    13,   628,   198,
          4342,    11,   423,   257,   804,    25,   628,   198,  5450,  1378,
          2503,    13,  1831,    13, 12567,    13,   785,    14,    42,   343,
          1525, 22480,    14,    70,  9945,    14,  9866,    14, 39358,    62,
            41, 10116,  1921,  3528,    13,  9132,   628,   198,  5574,   655,
          1011,   257,   804,   379,   428,  2443,    25,   628,   198,  5450,
          1378, 12567,    13,   785,    14,    38,   648,    75,   666,    54,
           648,    14,  5235,  1872,   628,   198, 13828,   468,   257,  3236,
          1351,   286,   477,   262,   474,   615,  

In [32]:
tokenizer.decode(output[0])


'This is good resource for geneai,\nand its really helpful, if you do it manually but with the aid of tools like gdb there are a lot of steps to take to make geneai a simple tool but the tool itself.\n\n\nHere, have a look:\n\n\nhttps://www.raw.github.com/KirbyFan/gdb/master/Gene_JAVASIG.md\n\n\nOr just take a look at this page:\n\n\nhttps://github.com/GanglianWang/genai\n\n\nWhich has a huge list of all the javasig'

In [35]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# Check if GPU is available, otherwise use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load pre-trained GPT-2 model and tokenizer
model_name = "gpt2-large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)


def generate_text(input_text, max_length=16, num_beams=5, do_sample=False, no_repeat_ngram_size=2):
    """
    Generate text based on the given input text.

    Parameters:
    - input_text (str): The input text to start generation from.
    - max_length (int): Maximum length of the generated text.
    - num_beams (int): Number of beams for beam search.
    - do_sample (bool): Whether to use sampling or not.
    - no_repeat_ngram_size (int): Size of the n-gram to avoid repetition.

    Returns:
    - generated_text (str): The generated text.
    """
    # Encode the input text and move it to the appropriate device
    input_ids = tokenizer(input_text, return_tensors='pt')['input_ids'].to(device)
    # Generate text using the model
    output = model.generate(input_ids, max_length=max_length, num_beams=num_beams,
                            do_sample=do_sample, no_repeat_ngram_size=no_repeat_ngram_size)
    # Decode the generated output
    generated_text = tokenizer.decode(output[0])
    return generated_text


def generate_text_with_nucleus_search(input_text, max_length=32, do_sample=True, top_p=0.9):
    """
    Generate text with nucleus sampling based on the given input text.

    Parameters:
    - input_text (str): The input text to start generation from.
    - max_length (int): Maximum length of the generated text.
    - do_sample (bool): Whether to use sampling or not.
    - top_p (float): Nucleus sampling parameter.

    Returns:
    - generated_text (str): The generated text.
    """
    # Encode the input text and move it to the appropriate device
    input_ids = tokenizer(input_text, return_tensors='pt')['input_ids'].to(device)
    # Generate text using nucleus sampling
    output = model.generate(input_ids, max_length=max_length, do_sample=do_sample, top_p=top_p)
    # Decode the generated output
    generated_text = tokenizer.decode(output[0])
    return generated_text


if __name__ == "__main__":
    # Example usage
    input_text = "I'm feeling well"
    generated_text = generate_text(input_text)
    print("Generated text:", generated_text)

    input_text = "This is a good resource for geneai, and it's really helpful"
    generated_text = generate_text_with_nucleus_search(input_text)
    print("Generated text with nucleus search:", generated_text)


The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Generated text: I'm feeling well," he said. "It's just a matter of getting
Generated text with nucleus search: This is a good resource for geneai, and it's really helpful to see what others have done. But there's still room for improvement. The first problem


In [ ]:
import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# Check if GPU is available, otherwise use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load pre-trained GPT-2 model and tokenizer
model_name = "gpt2-large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)


def generate_text(input_text, max_length=16, num_beams=5, do_sample=False, no_repeat_ngram_size=2):
    """
    Generate text based on the given input text.

    Parameters:
    - input_text (str): The input text to start generation from.
    - max_length (int): Maximum length of the generated text.
    - num_beams (int): Number of beams for beam search.
    - do_sample (bool): Whether to use sampling or not.
    - no_repeat_ngram_size (int): Size of the n-gram to avoid repetition.

    Returns:
    - generated_text (str): The generated text.
    """
    # Encode the input text and move it to the appropriate device
    input_ids = tokenizer(input_text, return_tensors='pt')['input_ids'].to(device)
    # Generate text using the model
    output = model.generate(input_ids, max_length=max_length, num_beams=num_beams,
                            do_sample=do_sample, no_repeat_ngram_size=no_repeat_ngram_size)
    # Decode the generated output
    generated_text = tokenizer.decode(output[0])
    return generated_text


def generate_text_with_nucleus_search(input_text, max_length=32, do_sample=True, top_p=0.9):
    """
    Generate text with nucleus sampling based on the given input text.

    Parameters:
    - input_text (str): The input text to start generation from.
    - max_length (int): Maximum length of the generated text.
    - do_sample (bool): Whether to use sampling or not.
    - top_p (float): Nucleus sampling parameter.

    Returns:
    - generated_text (str): The generated text.
    """
    # Encode the input text and move it to the appropriate device
    input_ids = tokenizer(input_text, return_tensors='pt')['input_ids'].to(device)
    # Generate text using nucleus sampling
    output = model.generate(input_ids, max_length=max_length, do_sample=do_sample, top_p=top_p)
    # Decode the generated output
    generated_text = tokenizer.decode(output[0])
    return generated_text


# Create Gradio interface
input_textbox = gr.Textbox(lines=7, label="Input Text", placeholder="Enter your text here...")
output_textbox = gr.Textbox(label="Generated Text", placeholder="Generated text will appear here...")

gr.Interface(
    [generate_text, generate_text_with_nucleus_search],
    inputs=input_textbox,
    outputs=output_textbox,
    title="Text Generation with GPT-2",
    description="Enter some text and generate new text using GPT-2 model.",
    allow_flagging=False
).launch()